### ISSUE TITLE
When changing master page or layout, content is missing, if another layout has no same regions

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1018]
Need to investigate more, need to consult with designers.

What can be done:
1) When inserting dynamic region, user can enter it's name
2) When inserting dynamic region, name can be generated for current page (e.g. dynamic-region-1, -2, etc ...)
3) When changing layout, if there is only one region in previous and the new layouts, contents can be moved to another region automatically
4) When changing layout, if there are more than one region, mapping form could be opened for mapping, how content  should be moved - need ability to assign source region and target region.

**Comment by smikulenas** [comment]
No longer relevant.
