### ISSUE TITLE
Media: error trying to edit image

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1154]
Upload any image -> open it -> save: Sorry. Internal server error occured. Please retry later or contact administrator.
Also image is not available in history

**Comment by daivabrazukaite** [comment]
1) It is not possible to remove crop.
Upload some image -> open it for edit -> crop some part -> save with override -> open for edit again -> click "Remove crop": crop will be removed, so press save with override again. Open for edit again: crop still exists.
Same if you save as new version after crop removing: no new version will be created and old cropped area will be provided.
2) "Save with override"/"Save as new version" are available even they should not after some crop was used and then removed.
Open not cropped image -> crop it -> remove crop: "Save with override"/"Save new version" still stay available. I think that in this case buttons should act the same like with image resize/size restore: only Save should be visible.

**Comment by daivabrazukaite** [comment]
Please after fix (-es) will be done, verify all functionality (developers + testers). Now i do not think that it is worth to test more as lots of things can be related and occur because of same reasons.

**Comment by smikulenas** [comment]
Fix available from 1.9.0-beta5+

**Comment by daivabrazukaite** [comment]
5) Error is received trying to restore initial image.
Upload image -> open, enter for example description and save again -> open history -> choose to restore initial version -> choose with override: error will be received, but version actually will be restored. Now make the same with new uploaded image, but choose to create new version: error will be received, new version for image will be created, but thumbnail version creation (?) will fail

**Comment by smikulenas** [comment]
Image override in content feature disabled (#1055), as current implementation is not in releasable state.
