### ISSUE TITLE
Extend JsIncludeDescriptor to support external JS files/modules

### ISSUE THREAD

**Issue by pauliusmaciulis** [devbridge/BetterCMS#1156]
Currently with the JsIncludeDescriptor it is possible to register only JS modules from the Better CMS server side module it self (JS files must be located in the module now). It needs to be updated to support external files as well - it should be possible to use the JsIncludeDescriptor to register a JS file/module from other locations (as CDNs, any domain, localhost). Do not forget to make sure that we need to support .min.js files as well.

For reference:
A) JavaScriptModulesHelper.RenderCommaSeparatedNamePathPairs() renders JS module paths in the  RenderMainJsFile.cshtml file.
B) The https://github.com/devbridge/BetterCMS/blob/dev/Modules/BetterCms.Module.Root/RootModuleDescriptor.cs file has the JsIncludeDescriptor(this, "knockout", "bcms.knockout-2.2.1.js", "bcms.knockout-2.2.1.min.js") as example of a complex JS file/module registration - it should be possible to do the same but from other locations (CDN, any domain, localhost).

**Comment by smikulenas** [comment]
Works fine.
