### ISSUE TITLE
Implement ability to remove security token warning messages when file storage isn't secured

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1157]
http://www.bettercms.com/support/bugs-and-suggestions/remove-current-storage-service-doesnt-support-token-based-security-message/

When file storage engine can;t be secured (e.g. file storage / FTP storage), message is shown: "Current storage service doesn't support token based security" 

Add a flag to cms.configuration for disabling such a message. By default it should be set to false.

**Comment by smikulenas** [comment]
Already implemented.

![image](https://cloud.githubusercontent.com/assets/2108569/10649110/cb1c1a7e-7807-11e5-81a2-b595a46bc4d6.png)
