### ISSUE TITLE
Refactor retrieving of page contents when rendering page

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1158]
There are few methods for retrieving pages and page contents with their children:
- GetPageToRenderCommand.GetPageContents
- GetPageToRenderCommand.GetPage
- ChildContentService.GetChildContents

Theese methods use .FetchMany() or Left.Join() multiple times.
If content has 10 options and 10 regions and 10 child contents, instead of 1 row, 10 * 10 * 10 = 1000 rows are returned.
There are some projects, where database result is up to 20Mb or more.

Use different logic instead of FetchMany (that problem occured, when trying to load contents with history, with options, with child regions with child contents), etc...

The best scenario - use Future values. It will return 10 + 10 + 10 = 30 rows instead of 10 * 10 * 10

**Comment by smikulenas** [comment]
For QA: we need to double check all the stuff related with page content (content in page, content in master page, content in widget, etc.).

**Comment by daivabrazukaite** [comment]
Description how widget regions should work:  #1090

**Comment by smikulenas** [comment]
Performance increased in some cases about 50%
