### ISSUE TITLE
Add description field to the author entity

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1166]
http://www.bettercms.com/support/bugs-and-suggestions/added-biography-type-property-to-an-author/

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+

**Comment by Audrunas** [comment]
Increase maximum field size up to maximum. Use textarea instead of input. When displaying the text, use crop.

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+

**Comment by daivabrazukaite** [comment]
UI issue: if some longer description text in page is presented, Name field is squeezed in grid while adding new record/editing some other record - see example for adding new item:
![bcms authoradd_edit](https://cloud.githubusercontent.com/assets/3446924/10815246/7a5d3b86-7e33-11e5-99b7-5e4a148fd7b9.jpg)

Also, maybe for saving space it would be worth to show image thumbnail resized same like it is in Media manager list?

**Comment by gerbenis** [comment]
Double check after #1393 is finished

**Comment by smikulenas** [comment]
No need to update for v2.0
