### ISSUE TITLE
Improve content overlays

### ISSUE THREAD

**Issue by paulgabronis** [devbridge/BetterCMS#1167]
Improved overlays added to Regions.cshtml file, ContentOverlay.cshtml is not used anymore.

To properly behave you should add "bcms-show-overlay" class on parent div (bcms-region-overlay) when clicking on sort content button (http://prntscr.com/506rpo) and "bcms-content-overlay" when hovering on main block, if "bcms-show-overlay" is added then "bcms-content-overlay" shouldn't be added as it's not needed.

Working branch: dev-overlay-improvement

**Comment by smikulenas** [comment]
Implemented. QA needed.

**Comment by Audrunas** [comment]
Fix is available in 1.11.0
