### ISSUE TITLE
IE11: widged editing - text selecting doesn't work fine

### ISSUE THREAD

**Issue by AukseJ** [devbridge/BetterCMS#1170]
http://bettercmsdemo.devbstaging.com/autumn/#
Actions: 
1. Site settings-> Widgets
2. Search "autumn" widget
3. Click edit

Result: when clicking on text in widget editing all text is marked. I can't move cursor in any place.
![widget](https://cloud.githubusercontent.com/assets/9379359/4806014/552a756a-5e84-11e4-93e3-2392cb6e3d7f.png)

**Comment by mantas-janulionis** [comment]
The issue is fixed, referenced commit is here: https://github.com/devbridge/BetterCMS/commit/54df63742a6e5c00a6636f02bc3ada41a5833466
