### ISSUE TITLE
Lucene Search Returns Html Comments in Search Results, also Style Node isn't excluded from search content.

### ISSUE THREAD

**Issue by ebalsami** [devbridge/BetterCMS#1175]
Update DefaultIndexerService: exclude HTMl contents and styles from HTML content. (append excludedNodeTypes array)
Review, which tags can be excluded also.

**Comment by mantas-janulionis** [comment]
There were separate tasks #1238 and #1215 . Both are fixed. Available in 1.10.0-beta8+
