### ISSUE TITLE
Encode Uploaded file URLs before saving to Database

### ISSUE THREAD

**Issue by mindaugas-zaluba** [devbridge/BetterCMS#1182]
When file is uploaded to cloud storage, and has special characters (i.e. spaces, +) The url saved is not encoded and has the same special characters.  Browsers know how to parse this, but  passing the string in back-end and creating requests is not possible without additional encoding.

**Comment by JuliusSenkus** [comment]
Uploaded files with ```"+"``` for example ```"26TestAndroidScreenImageTV _ + _.png"``` are with invalid urls, no matter how you encode it, it will be inaccessible because of **double escape sequence**, so we need to change physical file name in the start or allow double escape sequence in server.

**Comment by JuliusSenkus** [comment]
Now chars such as ```34 '"',60 '<',62 '>',124 '|',0 '\0',1 '',2 '',3 '',4 '',5 '',6 '',7 '\a',8 '\b',9 '\t',10 '\n',11 '\v',12 '\f',13 '\r',14 '',15 '',16 '',17 '',18 '',19 '',20 '',21 '',22 '',23 '',24 '',25 '',26 '',27 '',28 '',29 '',30 '',31 '',58 ':',42 '*',63 '?',92 '\\',47 '/'``` and ```space, +``` are replaced with underscore ```_``` also fixed bug when selected image for file after re-upload disapears.

**Comment by JuliusSenkus** [comment]
Fix available from 1.10.1+

**Comment by daivabrazukaite** [comment]
I'm not sure, so please check if this is as expected: uploaded image with with symbol which needs to be encoded, has not encoded value in bcms_media.Medias.PublicUrl.
Example: it was uploaded file with name &+&.png (staging db bcms_media.Medias.Id = EBB65602-CE20-4206-B32B-A51D010BA8F6); values in bcms_media.Medias:
- PublicUrl: http://bettercms.blob.core.windows.net/bettercmsstaging/image/bb76419154a343a2868d99e70a1ba14a/&_&.png
- FileUri: http://bettercms.blob.core.windows.net/bettercmsstaging\image\bb76419154a343a2868d99e70a1ba14a\%26_%26.png

**Comment by JuliusSenkus** [comment]
Yes it was expected, because while using local file storage IIS by default does not allow **double escape sequence**, so we must change those symbols to other symbols because otherwise even if they are encoded, double escape sequence error occurs.
