### ISSUE TITLE
Extend Categories

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1189]
Features:
 + support multiple lists of categories
 + support hierarchy under each category (i.e. child items can have parent-child relation between them)
 + category items should have the same "macrofield" functionality as sitemap nodes (for developers).
 + category tree it self should have "macrofield", too.

AC:
 + an admin can manage (create, edit, delete) multiple named lists of categories with child items/nodes or even without any items
 + an admin can create hierarchical trees of category nodes of unlimited depth under any category
 + API returns all categories in hierarchical structure.
 + API returns assigned categories for pages, blogs, widgets.

**Comment by smikulenas** [comment]
Update available from BetterCMS 1.10.0-beta1+

**Comment by daivabrazukaite** [comment]
i can't understand situation i faced - please investigate, do not change data and after investigation write what and why was happening:
- there is category "abc" which contains node a and its child b (and some more - see attachment)
![bcms abc category](https://cloud.githubusercontent.com/assets/3446924/6253381/881fea9e-b7a9-11e4-934e-6869d4d72bd0.jpg)

- there is one more category "a2" which contains nodes a1, its child a2, this one child a3 and so on till a5.
![bcms a2 category](https://cloud.githubusercontent.com/assets/3446924/6253382/8e01a1c8-b7a9-11e4-97d2-18522f10fa81.jpg)

So, total categories nodes list is: a, a1, a2, a3, a4, a5.
Open for example some page and enter "a" into categories input: correct list will be provided. Now choose for example "a2" from it -> again write "a" in input: now list is: a1, a3, a5, i.e. a and a4 are not available. Delete assigned a2 -> again write "a" and choose "a" as category -> write "a" again and look to the list: now a1, a2 and a5 are available and a3 and a4 are missing.

**Comment by daivabrazukaite** [comment]
2) Trying to edit deleted category (open categories list in two tabs, in one delete categoryX, in other try to open it for edit or save if you have it already opened etc.), 500 error is received.

**Comment by smikulenas** [comment]
Fixed in 1.10.0-beta5+

**Comment by daivabrazukaite** [comment]
Closed, as separate issues were created
