### ISSUE TITLE
Update Create/Register/Edit Widget UI to support multiple hierarchical categories

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1193]
After: #1189

AC:
 + in widget edit/create/register modal user can select / deselect multiple categories.

**Comment by smikulenas** [comment]
Update available from BetterCMS 1.10.0-beta1+

**Comment by daivabrazukaite** [comment]
Should be tested after  #1219 fix

**Comment by Deimante13** [comment]
I get internal server error when I put wrong widget path. The usual message "Widget view doesn't exists by given url (~c//test.csh). Url should start with tilde(~) and direct to views folder in the web application root folder (for example, ~/Views/Widgets/Example.cshtml). Check if url is valid and if file exists and try again. " should appear.
![1193](https://cloud.githubusercontent.com/assets/6420272/6749131/e9c50866-cef5-11e4-905b-dec3aba9eaa5.jpg)

**Comment by smikulenas** [comment]
Fix available from: 1.10.0-rc1+
