### ISSUE TITLE
Add new content types "Simple Text" & "Markdown" to current "Regular Content" and "Widget"

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1194]
As a developer I need a way to restrict page editor to add/edid only as text (not html) / in makrdown in specific layout region.

- [x] Markdown editor
- [x] Simple text editor

**Comment by pauliusmaciulis** [comment]
Add new tab "Simple Text" to the "Add New Content" dialog.
Reuse the "Regular Content" tab view using existing elements (content name, from-to dates, but instead of the riche text editor use the text area control.

**Comment by smikulenas** [comment]
After discussion within a team, we decided to split new content dialog into separate ones:
* Add Regular Content
* Add Simple Text
* Add Widget
In the page edit mode we will update '+' button with drop down arrow to add content and will add new button to insert widget.
![image](https://cloud.githubusercontent.com/assets/2108569/9957502/49b197f6-5e09-11e5-9c86-248343dad061.png)
CSS and JS edit should be moved to the separate tab and enabled only for Regular Content.

**Comment by Audrunas** [comment]
For the child widget option edit modal created new issue: #1335

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+
