### ISSUE TITLE
Azure storage deletes all the images from folder on cancel

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1195]
If media manager is using Azure Storage - and user on file upload dialog after uploading file will hit cancel - folder will be deleted. If new image is being uploaded - it's not the issue, but if this is performed for re-upload - all the history data of current image will vanish.

**Comment by JuliusSenkus** [comment]
Removed folder deletion from DefaultMediaImageService method RemoveImageWithFiles, left only file deletion cause if allowed on system to delete folder it would also delete all other images contained in that folder no matter if they are used, now only specific images are removed.

**Comment by smikulenas** [comment]
QA is needed.

**Comment by smikulenas** [comment]
Fix available from 1.10.1+
