### ISSUE TITLE
Old image is not showed after cancelling re-upload in properties

### ISSUE THREAD

**Issue by Deimante13** [devbridge/BetterCMS#1197]
Go to Media manager> Images> Select any image > Go to its properties> Re-upload new image there (no matter via drag or upload from computer) > After image is uploaded, press Cancel> You are back to Image properties window, but the old image is not showed.  
![bcms-1](https://cloud.githubusercontent.com/assets/6420272/5775723/888ed8ec-9d86-11e4-9488-4d0a170aacdc.jpg)

**Comment by smikulenas** [comment]
Fix available from 1.10.1+
