### ISSUE TITLE
Cross-site scripting (XSS) issue

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1200]
![image](https://cloud.githubusercontent.com/assets/2108569/5832580/fae894d8-a14f-11e4-9773-e1abc0332343.png)

**Comment by Adomavicius** [comment]
The goals of resolving this issue were:
* Prevent submitting invalid data;
* Prevent XSS attacks by encoding displayed user entered data that could be HTML;
* Prevent internal server errors from popping up when entering invalid data, as they do not allow the user to understand what exactly is wrong with their inputted data.

Issues that have been discovered:
* The [Tag list](https://github.com/devbridge/BetterCMS/blob/92b3e7efcd7b136e3307fb486ba1674281e67484/Modules/BetterCms.Module.Blog/ViewModels/Blog/BlogPostViewModel.cs#L169) in the BlogPostViewModel is impossible to properly validate as the tags are nothing but strings. I did not change this yet as the tag list is used in the [API](https://github.com/devbridge/BetterCMS/blob/fd1534dcf204ee0b998a80b676cccb1a1d55dddb/Modules/BetterCms.Module.Api/Extensions/BlogPostModelExtensions.cs#L35);
* A validation field is missing for the fields of the [user access list](http://puu.sh/hws06/d806ce69f7.png) in the Edit Page Properties menu. Right now, the field validates with a knockout, preventing it from submission, but no validation message is shown;
* As page titles allow HTML, there was an XSS issue with page suggestions in the Translations submenu of Edit Page Properties. I've fixed the issue by encoding text as it appears in the autosuggested list, however that caused an unwanted [side effect](http://puu.sh/hwsr7/bc02a7603a.png). I have yet to find a suitable fix for this while keeping the functionality of applying <strong></strong> around any matched characters.

**Comment by smikulenas** [comment]
For tags and translations leave it as is, but for user access control add validation message.

**Comment by Adomavicius** [comment]
Validation field added for User Access in Edit Page Properties. However, the style needs to be updated as the message exists within the DOM but is not visible to the user. (See image below)
After the style is updated the issue will be fully resolved.
![validation_message_incorrect_style](https://cloud.githubusercontent.com/assets/11733573/7450854/6869d49c-f252-11e4-8104-6c3026d4147b.jpg)

**Comment by Audrunas** [comment]
Fix is available from 1.11.0-beta0

**Comment by Audrunas** [comment]
@mantas-janulionis, could you fix, please, category node title to allow underscores and spaces?

**Comment by mantas-janulionis** [comment]
Fix is available from 1.11.0-beta05+

**Comment by KarolisBab** [comment]
1. JS is still executed if it is in content name when you try to delete such content.
2. JS is executed when saving New Master Page (if it is entered as name).

**Comment by gerbenis** [comment]
Fix will be available from 1.11.0-beta13+
