### ISSUE TITLE
IE11: word "download" all should be in the same line

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1207]
![image](https://cloud.githubusercontent.com/assets/2108569/6145226/3a42c722-b1e8-11e4-9786-bd88c6b32bfb.png)

**Comment by pauliusmaciulis** [comment]
Expand all dialogs.

**Comment by smikulenas** [comment]
@JuliusSenkus please double check if this is still relevant.

**Comment by JuliusSenkus** [comment]
It is fixed in newest version.

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+
