### ISSUE TITLE
Update Lucene search module with ability to skip indexing parts of page.

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1215]

**Comment by mantas-janulionis** [comment]
3 new optional configuration keys were added under `<search>` section:
LuceneExcludedNodes - for excluding DOM nodes
LuceneExcludedIds - for excluding DOM nodes with specified Ids
LuceneExcludedClasses - for excluding DOM nodes with specified classes

Excluded nodes will not be indexed and won't appear on search results.

Multiple configuration values should be provided separated by a comma (whitespaces will be trimmed)

Example. Configuration:
`<add key="LuceneExcludedNodes" value ="b"/>`
`<add key="LuceneExcludedIds" value="sample"/>`
` <add key="LuceneExcludedClasses" value="no-index, dont-index"/>`


Content:
`<b>content</b><div id="sample">content</div><div class="no-index">content</div><p class="dont-index">content</p>`

This will result in none of the 'content' being indexed and retreived in search

**Comment by smikulenas** [comment]
Available from 1.10.0-beta5+
