### ISSUE TITLE
MediaManager: search by "[save]" does not work

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1216]
1. Upload file
2. Rename it to "Title [save]"
3. Try to search by "[save]"
Expected: one file to be found
Actually: all files are returend

**Comment by smikulenas** [comment]
Fix available from 1.10.0-beta7+

**Comment by Deimante13** [comment]
1. Rename any existing image/file - or some images/files to "Title [save]".
3. Rename file/files again into some "[Title]".
4. Search by '[save]'. You will get a message:
"No matches found for "[save]".
Try searching again in older versions of media items."
5. Press on 'Try searching again in older versions of media items'. The file/files that had '[save]' in title earlier will appear.
6. Sort by column 'File Name' or 'File Type'. It will return to the message "
No matches found for "[save]".
Try searching again in older versions of media items.". 

If there was only one file found, it should show the same file after sorting. If there were several files found, it should sort by chosen column: File Name or File Type.

**Comment by Deimante13** [comment]
Also please add space in 'Collapse All': Edit Category> Nodes> CollapseAll

**Comment by JuliusSenkus** [comment]
Fixed also added option in filter "Include history items" that user could disable it ("Try searching again in older versions of media items.") if not needed.

**Comment by JuliusSenkus** [comment]
Fix available from 1.10.3-beta9+

**Comment by daivabrazukaite** [comment]
1) Either naming in filter should be changed or logic as now as a user i expect that if "Include history items" is checked on, search will be done in current + historical naming (i.e. same like "Include archived items") , but now it is not and search is done only in history versions. 
2) If search is done already using historical naming and no results are found "Try searching again in older versions..." is presented. I think it should appear only in case if search is done among current versions.

**Comment by JuliusSenkus** [comment]
Fixed, for # 1 changed name.

**Comment by JuliusSenkus** [comment]
Fixed all above and fix available from 1.10.4-beta3+
