### ISSUE TITLE
Extended categories: roles issues

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1220]
1)  BcmsAdministration: is not able to use categories in Media manager filtering, widgets add/edit, master pages add/edit
Should be: Admin should be able to use extended categories. Also, i'm not sure if he should not be able even to have full access to them, as categorization is also needed for widgets/master pages.
2)  BcmsDeleteContent: is not able to use categories in pages, blogs, media filtering
3)  BcmsPublishContent: is not able to use categories in pages/blogs filtering
Should be for #2 and #3: user with assigned role should be able to use extended categories in data filtering

**Comment by smikulenas** [comment]
1) BcmsAdministration: can manage categories (updated).
2) BcmsDeleteContent: fixed.
3) BcmsPublishContent: fixed.

Update available from 1.10.0-beta7+
