### ISSUE TITLE
Extended categories: non-unique item names usage issue

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1221]
Currently it is allowed to have items with non unique names (i think it is ok), but to use such an item is quite a tricky thing, as items in categories list contains only names and if you have items with same name in some different categories (or even inside the same), you are not able to understand if your chosen item is the one you needed.
Please think about this

**Comment by daivabrazukaite** [comment]
By the way, like a work around in stream app, we used unique names, but had one more field called "Public name" which was used for public view, i.e. inside admin part always unique names were used for making things clear.

**Comment by Adomavicius** [comment]
#1210 Is the task that is the solution to this issue.
