### ISSUE TITLE
Extended categories: no macro fields are available

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1223]
From #1189 AC:
category items should have the same "macrofield" functionality as sitemap nodes (for developers).
category tree it self should have "macrofield", too.

Now there is Macro field in related db tables, but there is no fields available in UI. Please double check requirements.

**Comment by smikulenas** [comment]
To show macro fields update the cms.config file:
![image](https://cloud.githubusercontent.com/assets/2108569/6288056/fbc7b578-b91e-11e4-8f6c-2c6bff94bf19.png)
