### ISSUE TITLE
Extended categories: added to filter categories are not removed after clearing filter values

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1228]
Media manager (no matter files or images) -> add at least one category into filter -> press Clear: category won't be removed.

**Comment by mantas-janulionis** [comment]
Fixed along with commit https://github.com/devbridge/BetterCMS/commit/c30bfc93cf7bee5705c4806ae631b89a4e17276b . See task #1225

**Comment by smikulenas** [comment]
Update will be available from 1.10.0-beta7+
