### ISSUE TITLE
Page structure: same content is provided twice

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1229]
Open home page in staging -> click on content management icon (near add new content icon) -> choose Manage: CMSMAINCONTENT is visible twice and in both sections same content is provided (see attachment). I'm not sure if there was some issue related with this and now it is fixed (but as result such a situation is still left), or this is something unknown yet. Please check
I'm not able to try to reproduce this issue as currently it is not possible to add any content to page (because of #1227).
![bcms contentstructure](https://cloud.githubusercontent.com/assets/3446924/6288459/e9944c06-b921-11e4-8643-fc6edb342464.jpg)

**Comment by smikulenas** [comment]
Related with master containing content with region called `CMSMainContent`.
![image](https://cloud.githubusercontent.com/assets/2108569/6290321/ad061136-b92e-11e4-84f5-c853c82e8f83.png)

**Comment by smikulenas** [comment]
This is the way it should work. If user does not want to see identical region names - region naming should be unique (but we do not force unique region naming).
