### ISSUE TITLE
Extended categories: if widget is not assigned to any category, it is displayed twice in widget selection 

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1233]
If widget has no assigned category, it is displayed in "Uncategorized" section in add new content -> widget tab. But, after extended categories functionality was implemented, such a widgets are displayed twice - see attachment
![bcms widgetsduplication](https://cloud.githubusercontent.com/assets/3446924/6330088/23dd4832-bb7e-11e4-886e-32df2bdc34c2.jpg)

**Comment by smikulenas** [comment]
Fix available from 1.10.0-beta7+
