### ISSUE TITLE
Extended categories: widgets are still visible assigned to category, which tree is deleted

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1234]
Current approach is such as, that after deleting category tree, all nodes that are assigned to it are not marked as deleted. I haven't found any other issues related with this, except the one: if some not deleted widget is assigned to category which belongs to deleted tree (i.e. category node itself is not deleted, but its tree is), this category is available in add new content -> widgets list. 

Steps to reproduce: create some category tree -> add at least one category node to it (further node1) -> assign some widget to node1-> delete category tree -> open for example any page -> add new content -> widgets: node1 is available in the list with assigned widget.

**Comment by smikulenas** [comment]
Fix available from 1.10.0-beta7+

**Comment by daivabrazukaite** [comment]
Now widget is not available in new content adding tab if it is assigned to deleted category until new published same widget version won't be created.
Steps: create category (category1) with some node assigned to it (node1) -> assign some widget (widget1) to node1 -> add new content from any page/blog/master -> widgets -> search for widget1 (no matter using search input or just by scrolling): widget1 will be available ok under node1 category. Delete category1 -> add new content again -> widgets -> search for widget1: it won't be available. Open widget1 -> save as published and execute same content adding steps: now widget will be found.

**Comment by JuliusSenkus** [comment]
Fix available from 1.10.3-beta5+

**Comment by daivabrazukaite** [comment]
It was missed situation then not whole category tree, but just it node with assigned widget is deleted - in this case widget is not available in "Select widget" modal.
Steps: create category1 -> add node1 under it -> assign widget1 to node1 -> open for edit category1 and delete node1 -> open "Select widget" and search for widget1: it won't be available.

**Comment by mantas-janulionis** [comment]
Fix is available is version 1.11.0-beta05+
