### ISSUE TITLE
Implement categories export/import for blogs

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1235]
Need to support hierarchical structure.

**Comment by JuliusSenkus** [comment]
Implemented, all categories imported with blogs are created as new and by current structure we are using (```BlogML```) I can't save category tree assignable options, so all items will be assignable to new imported categories (widgets, blogs etc) also hierarchy is saved, but order of categories in the same level is not saved.

**Comment by JuliusSenkus** [comment]
Fix available from version 1.10.3-beta7+

**Comment by jarektr** [comment]
Unsubscribe me immediately
5 Ağu 2015 21:11 tarihinde "JuliusSenkus" <notifications@github.com> yazdı:

**Comment by JuliusSenkus** [comment]
Added functionality that only related categories with selected blogs are imported. Fix available from version 1.10.3-beta9+

**Comment by daivabrazukaite** [comment]
Used for testing file with exported and now tried to import categories structure can be found http://bettercmsdemo.devbstaging.com/bcms-media/Files/Download?id=68474663-4d65-4968-9b42-a4ff00fe7465.
Next issues exists:
1) Upload file and choose to import all blogs (i.e. default setting): error is received. Full exception http://bettercmsdemo.devbstaging.com/bcms-media/Files/Download?id=6d68ccdd-2b5c-4f0c-bec3-a4ff00fe828a 
2) Upload file and choose to import for example file "Blog 0525 1" that has assigned one category: blog import will be done successfully, but category won't be created and won't be assigned to this blog.

**Comment by JuliusSenkus** [comment]
Finished, fix available from 1.10.4-beta6+
