### ISSUE TITLE
MediaManager: Categories are not being cloned while creating history version of Image/File.

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1239]
After fixing this issue, please verify if #1208 works OK (if not - fix it).

**Comment by mantas-janulionis** [comment]
Duplicate with #1236.

**Comment by smikulenas** [comment]
Fix available from 1.10.0-beta8+

**Comment by smikulenas** [comment]
Creating history item via API - categories are not cloned.

**Comment by smikulenas** [comment]
2bdf3109fe7bd0810ea8c21aa66b841d409566f2

**Comment by smikulenas** [comment]
Update available from version 1.10.0-beta9
