### ISSUE TITLE
Invalid hieroglyphs input in editor source mode.

### ISSUE THREAD

**Issue by mantas-janulionis** [devbridge/BetterCMS#1242]
It is impossible to type hieroglyphics properly in editor source mode.
I've tested with Korean and Japanese languages, but the actual problem may apply to more languages where a single character is typed by more than one keyboard button click.

For example trying to write the word 안녕하세요 results in ㅛㅇㅔㅅㅏㅎㅇㅕㄴㄴㅏㅇ.
You can reproduce this issue by setting your language to Korean and typing the letters "dkssudgktpdy" on QWERTY keyboard.

Reported by Kim in support forum http://www.bettercms.com/support/bugs-and-suggestions/foreign-language-in-source-view-problem/

**Comment by smikulenas** [comment]
Update available from 1.10.0-beta9+
