### ISSUE TITLE
Default widget option values are taken if widget is added via content.

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1243]
http://www.bettercms.com/support/widgets-and-modules/widget-options-not-populating-when-published/

![image](https://cloud.githubusercontent.com/assets/2108569/6777916/af23abd2-d156-11e4-971c-f4c1cc9f8820.png)

**Comment by mantas-janulionis** [comment]
Fix will be available in 1.10.0-rc1+

**Comment by smikulenas** [comment]
Tested - works fine.
