### ISSUE TITLE
Ordering(sorting) does not work for the same widget added multiple times to one region

### ISSUE THREAD

**Issue by RytisCapas** [devbridge/BetterCMS#1244]
Steps to reproduce:
* Create a server side widget( probably it's the same with html widgets).
* Create a layout with a region.
* Create a page using the layout.
* Add the same widget multiple times to the region in the page.
* You can assign different options to the inserted widgets to differ them for each other.
* Turn on sorting mode and try to change their order.

Order doesn't change in the database.

Tested on versions: 1.9.1, 1.8.3, 1.8.2

![list preview](https://cloud.githubusercontent.com/assets/3921271/6784316/ae61ea3e-d187-11e4-86a1-9d7305e430cf.png)
![list sorting view](https://cloud.githubusercontent.com/assets/3921271/6784321/b0b21eb2-d187-11e4-9c9a-100f0216efd7.png)

**Comment by smikulenas** [comment]
Fix available from 1.10.0-rc1+
