### ISSUE TITLE
Esc button does not work

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1246]
Steps to reproduce:
-          Open Site settings
-          Click on Page layouts section
-          Try to delete any template which is in use
-          An error message is displayed
-          If you press ESC, the modal does not close
-          Click on any other section
-          If you press ESC, the modal closes now

**Comment by Adomavicius** [comment]
I couldn't reproduce this issue. Tried on FF, Chrome, IE, Opera and Safari, seems to work on all of these browsers.
