### ISSUE TITLE
Add text area as option type

### ISSUE THREAD

**Issue by paulgabronis** [devbridge/BetterCMS#1248]
Would be nice to have textarea as widget option for the simple HTML widgets,
Now we have only text input field which is not very useful if someones want to add more text like short description.

![mrr3cah](https://cloud.githubusercontent.com/assets/2255639/6939922/2ae7bdc4-d87a-11e4-9205-a6e92345a814.png)

**Comment by Audrunas** [comment]
Add very long text - all the text will be visible. Should be visible only cropped text.

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+
