### ISSUE TITLE
Category(Categories?) Id not passed to page slug generation helper

### ISSUE THREAD

**Issue by RytisCapas** [devbridge/BetterCMS#1251]
Since 1.10.0 update categoryId is no longer passed to the "GeneratePageUrl" Helper.
Seems like it needs to be updated to handle a list of Ids.
![changeurlslug categoryid always undefined](https://cloud.githubusercontent.com/assets/3921271/6944975/34bee2f8-d89f-11e4-830b-0cf88f26a8cb.png)

It is used on our projects to generate a specific url prefix based on selected post category, for example "/news/", "/articles/", "/careers/".

![generatepageurl watcher](https://cloud.githubusercontent.com/assets/3921271/6944974/34bdc77e-d89f-11e4-9ac7-b27e6d02b2b9.png)

![pageurlgenerationrequest](https://cloud.githubusercontent.com/assets/3921271/6944973/34bc2b76-d89f-11e4-844e-0059e39a423f.png)

**Comment by smikulenas** [comment]
Fix will be available from 1.10.0+
