### ISSUE TITLE
CMS API BlogPosts.Get no longer supports filtering by "CategoryName"

### ISSUE THREAD

**Issue by RytisCapas** [devbridge/BetterCMS#1252]
Since 1.10.0 update CMS API  BlogPosts.Get(GetBlogPostsRequest request) no longer supports filtering by "CategoryName", after looking at BCMS source code looks like it works with CategoryId only.

Not sure if this is a bug or intentional update.

**Comment by smikulenas** [comment]
Fix will be available from 1.10.0+
