### ISSUE TITLE
As a user I want to be able to select categories without typing.

### ISSUE THREAD

**Issue by RytisCapas** [devbridge/BetterCMS#1253]
Since BCMS version 1.10.0.
There is no way to see a list of categories or select/create them from edit/create page views, you have to remember the category name.

Looks like they were implemented in the same way as page tags, but tags can be created directly while editing or creating a page by just typing a new tag in and pressing enter, this does not work for categories.

**Comment by smikulenas** [comment]
Add drop-down list with auto-complete and infinite scroll.

**Comment by smikulenas** [comment]
Design is needed for categories assigning for PageProperties.

**Comment by smikulenas** [comment]
#1419
