### ISSUE TITLE
Language code is not available in master page widget 

### ISSUE THREAD

**Issue by mantas-janulionis** [devbridge/BetterCMS#1257]
When a widget is placed into a master page, and the page has a language assigned, the widgets do not display that language.

To reproduce: Create a server side widget that outputs language code from render widget view model -> create a master page and place that widget inside -> Create a new page based on the master page -> Language code will be null

There have been workarounds to query api within the widget to retrieve page properties including language, but that results in an decreased performance.

I think we could tune page rendering to set page language id right away.

**Comment by JuliusSenkus** [comment]
Bug appears only when last (master) page is rendered, then language value is not copied to new rendered page.
Fix available from 1.10.3-beta10+
