### ISSUE TITLE
CMS not working in Visual Studio 2010 on Windows XP

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1258]
Server Error in '/' Application.

Stack Trace: [ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.] System.Collections.Generic.List1.Insert(Int32 index, T item) +49 System.Collections.ObjectModel.Collection1.InsertItem(Int32 index, T item) +48 System.Web.Mvc.ViewEngineCollection.InsertItem(Int32 index, IViewEngine item) +91 System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item) +116 BetterCms.Core.CmsContext.LoadAssemblies() +675 BetterCms.Core.Environment.ApplicationStart.BetterCmsEntrypoint.PreApplicationStart() +624

[CmsException: Failed to load assemblies.] BetterCms.Core.Environment.ApplicationStart.BetterCmsEntrypoint.PreApplicationStart() +705

[InvalidOperationException: The pre-application start initialization method PreApplicationStart on type BetterCms.Core.Environment.ApplicationStart.BetterCmsEntrypoint threw an exception with the following error message: Failed to load assemblies..] System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +423 ...

[HttpException (0x80004005): The pre-application start initialization method PreApplicationStart on type BetterCms.Core.Environment.ApplicationStart.BetterCmsEntrypoint threw an exception with the following error message: Failed to load assemblies..] System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9091436 System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +97 System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +256

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.547

http://www.bettercms.com/support/installation/not-working-in-visual-studio-2010-on-windows-xp/

**Comment by Adomavicius** [comment]
This happens because of the outdated Newtonsoft.Json package that BetterCMS uses. (Version 5.0.8, when the newest stable release is 6.0.8).
Until a newer version of the package is used in BetterCMS, the fix is to run the Install-Package Newtonsoft.Json command in Nuget package manager console.

**Comment by smikulenas** [comment]
#1265

**Comment by alhamdi23** [comment]
I still have same problem even if I add Install-Package Common.Logging
