### ISSUE TITLE
Add "Create Master" button in side menu when user is in master page.

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1264]

**Comment by JuliusSenkus** [comment]
Fix available from v1.10.4-beta1+

**Comment by JuliusSenkus** [comment]
Also button Create Master is only shown in master pages to users who have edit rights, on press it opens create master page modal with preselected current master page.

**Comment by daivabrazukaite** [comment]
After new master using side panel is created, i think it would be logical to make redirect to this newly created master (now modal is simply closed and user is left in same master as he was).

**Comment by JuliusSenkus** [comment]
Fix available from 1.10.4-beta2+
