### ISSUE TITLE
Failed to process file

### ISSUE THREAD

**Issue by fenoktaye** [devbridge/BetterCMS#1268]
Hi, 
I'm using BetterCMS with love <3,

But i'm getting "Failed to process file" error on file upload no matter of type.
I have no problem on localhost. It must be a server error. The /uploads folder has permissions to read and write. I can write with System.IO.

There must be another problem but i cant get any error messages.
I enabled logs but it contains only not found image errors.

PS : CMS is making  image paths like /uploads/ımage instead of /uploads/image ( this is not the reason of error . I checked file upload with a txt file, same error. )

**Comment by smikulenas** [comment]
Reopen if this is still relevant, please.

**Comment by fenoktaye** [comment]
This is solved by upgrading server from Windows 2008 to Windows 2012. Thanks for interest
