### ISSUE TITLE
Change migration scripts to not use MERGE statement

### ISSUE THREAD

**Issue by Adomavicius** [devbridge/BetterCMS#1272]
A [thread](http://www.bettercms.com/support/bugs-and-suggestions/invalid-objectname-bcms-root-widgetcategories/) on the Support Forum highlighted the fact that we recently started using 'MERGE' statements in our migration scripts, essentially dropping support for any SQL Server version under 2008.
The list of scripts that use the 'MERGE' statement are the following:
* [BetterCms.Module.Blog/Models/Migrations/Migration201502101139.sqlserver.sql](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.Blog/Models/Migrations/Migration201502101139.sqlserver.sql)
* [BetterCms.Module.Root/Models/Migrations/Migration201502061445.sqlserver.sql](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.Root/Models/Migrations/Migration201502061445.sqlserver.sql)
* [BetterCms.Module.Root/Models/Migrations/Migration201502101136.sqlserver.sql](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.Root/Models/Migrations/Migration201502101136.sqlserver.sql)
* [BetterCms.Module.Pages/Models/Migrations/Migration201502021540.sqlserver.sql](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.Pages/Models/Migrations/Migration201502021540.sqlserver.sql)
* [BetterCms.Module.Pages/Models/Migrations/Migration201502101138.sqlserver.sql](https://github.com/devbridge/BetterCMS/blob/dev/Modules/BetterCms.Module.Pages/Models/Migrations/Migration201502101138.sqlserver.sql)
* [BetterCms.Module.MediaManager/Models/Migrations/Migration201502101137.sqlserver.sql](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.MediaManager/Models/Migrations/Migration201502101137.sqlserver.sql)

The aforementioned scripts should be changed/replaced by scripts that do not use MERGE statements in order to support earlier versions of SQL Server.

**Comment by Audrunas** [comment]
Need to test

**Comment by Audrunas** [comment]
Tested, seems to be ok.
