### ISSUE TITLE
Content widgets do not display default master page options when placed in an inherited page

### ISSUE THREAD

**Issue by Adomavicius** [devbridge/BetterCMS#1276]
Issue discovered from: http://www.bettercms.com/support/bugs-and-suggestions/using-page-options-in-a-content-widget/

In order to reproduce:

1. Create master page with a content region;
1. Add option with a default value to the master page;
1. Create a page that inherits the master page;
1. Create a content widget that uses a smart tag to output the option defined in the master page;
1. Put the content widget in the inherited page;
1. Notice that if the 'Use default' option is checked in the inherited page the content widget does not display the default option.

---
# 'Use default' option disabled:
![Default option disabled](http://puu.sh/iuMsQ/1da388da5d.png)

---

# 'Use default' option enabled:
![Default option enabled](http://puu.sh/iuMuD/c796aee826.png)

**Comment by smikulenas** [comment]
Does this issue still exist in 1.11.0-beta16?

**Comment by daivabrazukaite** [comment]
Tested in 1.11.0-beta17: issue is not available there, so it is closed.
