### ISSUE TITLE
JavaScript file (defined by JS Include URL option type) gets rendered twice in the DOM when default option from Master page is selected

### ISSUE THREAD

**Issue by Adomavicius** [devbridge/BetterCMS#1279]
Steps to reproduce issue:
* Create new master page or use already created one;
* Set a new option in the master page with type 'JS Include URL' linking to a JavaScript file;
* Create new page that inherits the master page with the 'JS Include URL' option;
* Make sure that 'Use default' is checked in page options;
* The defined JavaScript file gets rendered twice in the DOM of the child page (see attached image).

![83f24c588a](https://cloud.githubusercontent.com/assets/11733573/8770710/623088c4-2ebf-11e5-8369-41b634f9ea70.png)

**Comment by JuliusSenkus** [comment]
Fixed in 1.10.3+
