### ISSUE TITLE
Search In Contents

### ISSUE THREAD

**Issue by MrHarry01** [devbridge/BetterCMS#1283]
Hi i have implemented Lucene Search its working fine only issue is when i search any contents with in pages its slow down the whole process, Its very  very slow kindly suggest something to optimize this and consider this on very high priority.
e.g

var req = new SearchPagesRequest();
     req.SearchString = parsedQuery[key.ToString()];
                        var search = api.Pages.Pages.Search(req);
                        foreach (var searchItem in search.Data.Items)
                        {
                            CMSSearchResult searchResult = new CMSSearchResult
                            {
                                Snippet = searchItem.Snippet,
                                Title = searchItem.Title,
                                Url = searchItem.FormattedUrl
                            };
                            result.SearchResults.Add(searchResult);
                        }
                        result.TotalCount = search.Data.TotalCount;

Can anybody help me on this.

**Comment by smikulenas** [comment]
Hi, which CMS  version you are using?
