### ISSUE TITLE
Delete widget: error that widget can not be deleted is presented in underlying page not in 'Select widget'

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1285]
Open widget selection modal called from CKEeditor (from page/html widget) -> choose to delete any widget that you know is used by some content and won't be deleted: spinner will appear and then disappear, no error message will be presented. Close modal: error that widget can not be deleted is presented in window from which this modal was called.

**Comment by JuliusSenkus** [comment]
Fix available from version 1.10.4-beta5+
