### ISSUE TITLE
Find Usages on Templates does not show usages from Master Pages

### ISSUE THREAD

**Issue by remyblok** [devbridge/BetterCMS#1286]
If you create a Master Page based on a Template and then look at the usages of the selected Template in the Site Settings, then the created Master Page is not shown as a usage of that Template. I would expect that the Master Page is also visible as a Usage of the template, so that I can easily find out all references. 
This is based on the latest version used directly from a Azure Deployment, seems to be version 1.8.2. Might have been fixed in a subsequent release?

**Comment by smikulenas** [comment]
Julius, please double check if this is relevant for the latest version.

**Comment by JuliusSenkus** [comment]
It is relevant you can't find usages of that master page if you search by that template.

**Comment by JuliusSenkus** [comment]
Sorry, missed checkbox option "Include master pages", with it search finds what is needed.

**Comment by remyblok** [comment]
Ahh okee! I missed that filter option. I totally overlooked it. Thanks for your reply!
