### ISSUE TITLE
After a fresh install on Azure via the WebApp-Catalog the web always shows a 500 error

### ISSUE THREAD

**Issue by Anheledir** [devbridge/BetterCMS#1295]
I did a fresh install via the Azure Portal, installing BetterCMS via the WebApp-Catalog. Everything worked fine and on first visit of the site I could create the first users and login with that user, too. After that every call to the Webpage results in a 500 server-error.

This is the detailed error-event-log:

Process information:
 Process ID: 4708
 Process name: w3wp.exe
 Account name: IIS APPPOOL\anheledirNET-BetterCMS

Exception information:
 Exception type: InvalidOperationException
 Exception message: The view 'Error' or its master was not found or no view engine supports the searched locations. The following locations were searched: ~/Areas/bcms-root/Views/Cms/Error.cshtml ~/Areas/bcms-root/Views/Shared/Error.cshtml ~/Views/Cms/Error.cshtml ~/Views/Shared/Error.cshtml ~/Areas/bcms-root/Views/Cms/Error.aspx ~/Areas/bcms-root/Views/Cms/Error.ascx ~/Areas/bcms-root/Views/Shared/Error.aspx ~/Areas/bcms-root/Views/Shared/Error.ascx ~/Views/Cms/Error.aspx ~/Views/Cms/Error.ascx ~/Views/Shared/Error.aspx ~/Views/Shared/Error.ascx ~/Areas/bcms-root/Views/Cms/Error.vbhtml ~/Areas/bcms-root/Views/Shared/Error.vbhtml ~/Views/Cms/Error.vbhtml ~/Views/Shared/Error.vbhtml bei System.Web.Mvc.ViewResult.FindView(ControllerContext context) bei System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) bei System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) bei System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.b__22(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) bei System.Web.Mvc.Controller.<>c__DisplayClass1d.b__18(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(IAsyncResult ar) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(IAsyncResult ar) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) bei System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) bei System.Web.Mvc.MvcHandler.<>c__DisplayClass8.b__3(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(IAsyncResult ar) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) bei System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) bei System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Request information:
 Request URL: http://anheledirnet-bettercms.azurewebsites.net/
 Request path: /
 User host address: 77.23.97.131
 User: Anheledir
 Is authenticated: True
 Authentication Type: Forms
 Thread account name: IIS APPPOOL\anheledirNET-BetterCMS

Thread information:
 Thread ID: 6
 Thread account name: IIS APPPOOL\anheledirNET-BetterCMS
 Is impersonating: False
 Stack trace: bei System.Web.Mvc.ViewResult.FindView(ControllerContext context) bei System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) bei System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) bei System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.b__22(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) bei System.Web.Mvc.Controller.<>c__DisplayClass1d.b__18(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(IAsyncResult ar) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(IAsyncResult ar) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) bei System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) bei System.Web.Mvc.MvcHandler.<>c__DisplayClass8.b__3(IAsyncResult asyncResult) bei System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(IAsyncResult ar) bei System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() bei System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) bei System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) bei System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Custom event details:

**Comment by smikulenas** [comment]
Hi, sorry for very late answer. Exact issue is totally not clear and should be logged somewhere at the beginning of the log file, so if you are still interested in find out, please share all the log file.
