### ISSUE TITLE
Tag casing issue

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1309]
When tags of different cases are enter in page properties (e.g. enter tag, Tag and TAG), exception occurs: [SQL: SQL not available] NHibernate.Exceptions.GenericADOException: could not execute batch command.[SQL: SQL not available] ---> System.Data.SqlClient.SqlException: Violation of UNIQUE KEY constraint 'UX_Cms_Tags_Name'. Cannot insert duplicate key in object 'bcms_root.Tags'. The duplicate key value is (Tag, <NULL>).
Violation of UNIQUE KEY constraint 'UX_Cms_Tags_Name'. Cannot insert duplicate key in object 'bcms_root.Tags'. The duplicate key value is (TAG, <NULL>).

**Comment by JuliusSenkus** [comment]
Now tags are added ignoring case, meaning "asd" and "ASD" are the same tag.
Fix available from 1.10.4-beta10+
