### ISSUE TITLE
CmsWidgetOption smart tag not working

### ISSUE THREAD

**Issue by theikell** [devbridge/BetterCMS#1313]
The documentation at https://github.com/devbridge/BetterCMS/wiki/Smart-tags does not list CmsWidgetOption as an available smart tag, however an example at https://github.com/devbridge/BetterCMS/wiki/Widgets-for-Developers mentions it. It also appears in the Smart Tags list in the HTML editor.

Is it a bug that this option does not work?

**Comment by smikulenas** [comment]
Hi, yes you are right - it's a bug in our documentation :smile: 

It definitely works for Html Widgets and should be used this way:
![screenshot_2](https://cloud.githubusercontent.com/assets/2108569/10072458/80c86808-62ca-11e5-9777-cd0399c5df59.png)

**Comment by theikell** [comment]
Thank you. Is it only intended to work with HTML widgets? I'm trying to use it in a server widget and it does not work. The CmsPageOption smart tag works in my server widget, but not the CmsWidgetOption smart tag.
