### ISSUE TITLE
Adding Route

### ISSUE THREAD

**Issue by jmalatia** [devbridge/BetterCMS#1314]
I been testing different CMS's for the past few days and I just made an empty MVC project and added BetterCMS to it from Nuget and followed the info in the wiki on the manual changes that needed to be made to project.  I got that to work, but I am now trying to add an auto generated Nav menu (is there something already built in for this?  if so, can't seem to find any info???).  Anyways, I used the BetterCMS.Demo as a reference and added a Sitemap Controller, Sitemap Views and MenuItemViewModel, but when I call `@{ Html.RenderAction("Index", "Sitemap", new { area = "" }); }` from our _Layout page, we get the error:

```
Server Error in '/' Application.

No route in the route table matches the supplied values.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: No route in the route table matches the supplied values.

Source Error: 


Line 9:      <header>
Line 10:         <nav class="page-navigation" id="site-nav">
Line 11:             @{ Html.RenderAction("Index", "Sitemap", new { area = "" }); }
Line 12:         </nav>
Line 13:     </header>

Source File: c:\users\xxx\documents\visual studio 2015\Projects\DebBetterCms\DebBetterCms\Views\Shared\Layouts\_LayoutPage1.cshtml    Line: 11 
```

And we have the following in our App_Start/RouteConfig.cs

```
using System.Web.Mvc;
using System.Web.Routing;

namespace DebBetterCms
{
    public class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            routes.MapRoute("menu-top", "Sitemap/Index", new { area = string.Empty, controller = "Sitemap", action = "Index" }, new[] { "DebBetterCms.Controllers" });

            // Below doesn't work either
                // routes.MapRoute("menu-top", "Sitemap/Index", new { area = string.Empty, controller = "Sitemap", action = "Index" });

            //routes.MapRoute(
            //    name: "Default",
            //    url: "{controller}/{action}/{id}",
            //    defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            //);

        }
    }
}

``` 

The route looks right to me?  Do I need to add the routes somewhere else? Any help?  

Thanks.

**Comment by smikulenas** [comment]
Hi, we have no menu widget by default: http://www.bettercms.com/support/widgets-and-modules/megamenu/

Regarding Controllers & Routing: from code perspective looks OK, add Route Debugger for deeper investigation. How to use it, please take a look [here](http://haacked.com/archive/2008/03/13/url-routing-debugger.aspx/).
[This](http://www.bettercms.com/support/installation/better-cms-with-areas/) also may help.
