### ISSUE TITLE
Enable static localizability of pages/widgets enhancement.

### ISSUE THREAD

**Issue by ebalsami** [devbridge/BetterCMS#1325]
It would be very helpful if you enable static localizability of pages/widgets.
By static information I mean all data that is not subject to user modification and that can be considered for the most part as not changeable. This includes text labels, error and information messages, help, and graphics that are spread throughout the user interface of the application.

**Comment by smikulenas** [comment]
Regarding this, please take a look at http://www.bettercms.com/support/using-bettercms/translating-bettercms-to-arabic-rtl-languages/

**Comment by ebalsami** [comment]
Thanks for your reply!  I don't mean this functionality. Many clients, which are not programmers, may sometimes want to change some labels (in resource files).
It is very annoying (for a developer), client to ask the developer to change the labels.
An admin widget where the user can manipulate these strings would be perfect. Also, a functionality that the developer will use in his/her code like GetLocalizedLabel("Contact.ErrorMessage") would be perfect.
