### ISSUE TITLE
Newsletter Widget -Download all subscribers enhancement.

### ISSUE THREAD

**Issue by ebalsami** [devbridge/BetterCMS#1326]
It would be very helpful if you implement a function "Download all Subscribers in a csv file" in admin area of newsletter widget.

**Comment by smikulenas** [comment]
Nice idea.

**Comment by JuliusSenkus** [comment]
Fix is available in 1.11+

**Comment by smikulenas** [comment]
@JuliusSenkus, merged this into DEV branch.

**Comment by smikulenas** [comment]
Fix available in 2.0.0-preview1+
