### ISSUE TITLE
Smart tags should be rendered in CSS / JS also

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1328]
There is a need to use smart tag in JS. For example, console.log('{CmsPageTitle}') should render page's title, nor {CmsPageTitle}

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+

**Comment by daivabrazukaite** [comment]
CSS styles are not applied if first item is specified using option (tested with page options). 
Steps: create some page -> add page option with type = text, name = option1,  value  = p. Add for example html content with some paragraph (for example <p>text1</p>) -> open css tab and add such a style: {{CmsPageOption:option1}} {color:green} h1 {color:blue} -> save (no matter as draft or published version): specified styles won't be applied. Open content css for edit again and move h1 before {{CmsPageOption:option1}} -> save: now styles will be applied.

**Comment by gerbenis** [comment]
1) Fixed
2) Smart Tag rendering in Widget CSS & JS is not supported, therefore "Insert Option" button behavior was changed to insert Page Option and "Widget Option" was removed from Smart Tags drop-down menu.

**Comment by smikulenas** [comment]
Fix is available in 1.11.0-beta08+
