### ISSUE TITLE
Update API: include all changes for multilingual widgets manipulation

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1333]
## Global
- [x] `OptionModel` / `OptionValueModel` (namespace: `BetterCms.Module.Api.Operations.`): add the list of translation models

## Page contents
- [x] Get page content by id (`GetPageContentRequest`): when retrieving options translated to the page language
- [x] Save page content (`PutPageContentRequest` / `PostPageContentRequest`): nothing to do
- [x] Get page content options (`GetPageContentOptionsRequest`): when retrieving options translated to the page language

## Server control widgets
- [x] Get server control widget by id (`GetServerControlWidgetRequest`): when retrieving options and child content options, retrieve option translations list also
- [x] Save server control widget (`PostServerControlWidgetRequest` / `PutServerControlWidgetRequest`): save option translations list if it's provided
- [x] Get server control widget options (`GetServerControlWidgetOptionsRequest`): when retrieving options, retrieve option translations list also

## HTML content widgets
- [x] Get HTML content widget by id (`GetHtmlContentWidgetRequest`): when retrieving options and child content options, retrieve option translations list also
- [x] Save HTML content widget (`PostHtmlContentWidgetRequest` / `PutHtmlContentWidgetRequest`): save option translations list if it's provided
- [x] Get HTML content widget options (`GetHtmlContentWidgetOptionsRequest`): when retrieving options, retrieve option translations list also

## Tests
- [x] Review tests for each request provided above.

**Comment by smikulenas** [comment]
We need to test this.
