### ISSUE TITLE
Markdown editor: add a button for a dialog for editing child widget options

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1335]
- Create HTML content or blog post content as markdown.
- Insert a widget to the content

There is no way to edit child widget options. 
When cursor is on the widget HTML, the button "Edit Child Widget Options" should appear.

**Comment by Audrunas** [comment]
Fix will be avaiable from 1.11.0-beta05+

**Comment by daivabrazukaite** [comment]
Issue exists only on Safari (tested on El Capitan/Safari9 and Yosemite/Safari8) 
If there is at least one row above widget - widget options button is available, but it doesn't open options modal. 
Steps:add new markdown content -> choose to insert widget -> choose any widget: Widget Options button will be available in toolbar, click on it will open child widget options edit modal (ok). Close modal and simply add empty line/any text before widget tags and try to open widget modal now: modal won't be opened.

**Comment by smikulenas** [comment]
Fix is available in 1.11.0-beta08+
