### ISSUE TITLE
Page placement to sitemap (after new page creation) not working

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1336]
![image](https://cloud.githubusercontent.com/assets/2108569/10518028/1ccf1fd4-7325-11e5-84ff-d2abc030e5bd.png)

**Comment by Audrunas** [comment]
Fix will be avialable in 1.11.0-beta04+

**Comment by daivabrazukaite** [comment]
If not all sitemaps fit into initial screen, it is not possible to navigate to them and add page there - see attachment.
![bcms sitemapsnavigation](https://cloud.githubusercontent.com/assets/3446924/10844911/5304c728-7f0c-11e5-9c0c-41e20a6d814b.jpg)

**Comment by daivabrazukaite** [comment]
P.s.: as this is not critical issue and now main functionality is working, removed 'critical' label

**Comment by smikulenas** [comment]
Issue exists because of one of sitemaps names are super log. No longer relevant to v2.0
