### ISSUE TITLE
Page widget option is shown incorrectly

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1337]
This is widget configuration:

![image](https://cloud.githubusercontent.com/assets/2108569/10518212/fa494fe2-7325-11e5-94be-455289bacd6a.png)

![image](https://cloud.githubusercontent.com/assets/2108569/10518230/0a1e4a08-7326-11e5-84e0-3dd70077c5eb.png)

![image](https://cloud.githubusercontent.com/assets/2108569/10518236/12fd4c3c-7326-11e5-9480-8f3c62f95bff.png)

This how it looks in LT page:

![image](https://cloud.githubusercontent.com/assets/2108569/10518166/bd9e31e8-7325-11e5-951e-976cdcad2364.png)

"Use Default Option" is shown incorrectly, too.

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta04+
