### ISSUE TITLE
Language selector: UI issues

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1340]
1) Edit widget: after type dropdown is presented, language selector is moved down and overlaps with table header (see attachment).  Also, on Chrome (versions 46.0 and 45)/Safari (versions 9 and 8)/Opera, if type dropdown is presented and other tab is opened after coming back to options and adding new option, language dropdown stays "stuck" with header (scenario: options -> add new -> open for example properties tab -> open again options -> choose type)
![bcms widgetoptionslanguagedropdown](https://cloud.githubusercontent.com/assets/3446924/10540287/592e5e32-740f-11e5-8cdc-af69637f525a.jpg)

2) Edit sitemap -> Nodes: language selector is too high 
Same in site map history

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta04+
