### ISSUE TITLE
Widget: exception if option with imageUrl or imageFolder is added

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1341]
Widget options -> add new -> choose type "Image URL" -> enter name and try to save widget: exception. Same with "Image Folder" type

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta4+

**Comment by daivabrazukaite** [comment]
As now it is possible to create options with mentioned types, issue is closed and separate bugs related to folder value are created (#1412, #1411)
