### ISSUE TITLE
Widget: option update instead of insert can be done if old option is deleted and new one with same name created

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1343]
Edit widget -> options -> create new option for default language, add different translation for lang1  -> save widget -> open for edit -> options -> delete option -> add new option with same name as just deleted option -> save widget -> open for edit once more -> options -> change language to lang1: value set for deleted option will be displayed. 
Attachment with example then such a scenario can complicate things is added:
![bcms optionupdateinsteadofinsert](https://cloud.githubusercontent.com/assets/3446924/10543269/20231828-7426-11e5-9b0b-6610eb9f663c.jpg)

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta04+
