### ISSUE TITLE
Widget: if option is renamed with new widget version creation, two options as separate records will be available in this new version

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1344]
Add widget -> options -> add new option 'option1'-> save and publish widget -> open it for edit -> options -> rename 'option1' to 'option2' -> save as draft/save and publish -> open widget for edit again -> options: now 'option1' and 'option2' are provided as separate options.

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta04+
