### ISSUE TITLE
Widget: option translations are not versioned

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1345]
I found no information regarding options translations versioning, so please check if current behavior then options are versioned, but translations are not is correct one (i think that each version should contain full information which could be restored)

**Comment by Audrunas** [comment]
There is an issue created in the next milestone: https://github.com/devbridge/BetterCMS/issues/1319
The history will be implemented as soon as possible

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta04+
