### ISSUE TITLE
Assign widget: same widget can be provided more than once in selections list

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1348]
Create and publish some html widget (further widget1) -> open it for edit and save as draft -> open "Select widget" (for example from page choose to add widget as content) -> search for widget1: same record will be presented twice - see attachment
![bcms publishedwidgetwithdraft](https://cloud.githubusercontent.com/assets/3446924/10583483/ec00d2ac-7695-11e5-9339-36f0253def4d.jpg)

**Comment by Audrunas** [comment]
Fix will be available from 1.11.0-beta05+
