### ISSUE TITLE
Widget: incorrect value is used if there is at least one translation but not for page language

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1350]
Create widget1 with for example text option1 with value "text" as default one and no translations -> make this option value visible in html (use CmsWidgetOption) -> save and publish widget1 -> create widget2 -> insert widget1 into it -> right click on widget1 container and choose "Edit widget options" (i.e. child widget options will be opened) -> choose language1 -> check Use Default = NO and enter some different text (for example "textLanguage1") -> close -> save and publish widget2 -> add widget2 to some page as content and try changing page languages: option value will be visible only for language1 and for all other languages, no value will be presented even actually "text" should be displayed as it wasn't specified differently for these languages.
P.s.: correct values changing language in child widget options will be presented.

**Comment by mantas-janulionis** [comment]
Fix is available is 1.11.0-beta05+
