### ISSUE TITLE
Thick line needs to be thin (simple text editing)

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1353]
![image](https://cloud.githubusercontent.com/assets/2108569/10611517/115e4896-7712-11e5-821c-3f04368557ae.png)

**Comment by Audrunas** [comment]
Commit: https://github.com/devbridge/BetterCMS/commit/201b2f2237642a6143ddea2dda33a63f72b88b2c

**Comment by Audrunas** [comment]
Fix will be available from 1.11.0-beta05+
