### ISSUE TITLE
Page structure management: not all content types are available for all regions

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1388]
Create new page using 3 regions (you can use simple Default template): check content options for all regions - markdown and plain text will be available for all (ok). Open page structure management modal (Manage button) and now check contents type availability: header and main content regions will contain only HTML and Markdown options, footer - all four types. Add some for example html content to main content region and now check options: now all four will be available for it (same with header)

**Comment by gerbenis** [comment]
Same as #1389, since all content options are actually there, but the drop-down list is hidden underneath the following regions.

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta11+
If issue still exists, please reopen it and move into milestone v2.0
