### ISSUE TITLE
Page structure management: UI issues with add content for widget

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1389]
Add widget which contains dynamic region and for example html to some page main content region ->  open this page structure modal: you should see something like in attachment bellow:
![cms pagestructureinitial](https://cloud.githubusercontent.com/assets/3446924/10787236/e3882fb0-7d77-11e5-8ba7-fecba5316973.jpg)
Click on "Add content" button in widget area:
1) Not all menu items will be visible as menu will be overlapped with next section - see attachment
![cms pagestructurewidgetcontentmenu](https://cloud.githubusercontent.com/assets/3446924/10787280/62751040-7d78-11e5-9992-e8485b33e8cc.jpg)
2) Menu is stuck and it is not possible to collapse it. Also if some content under this widget already exists, because of stuck menu it won't be possible to use its management options as they will be under menu.
3) Open some page with two regions one under other into which content adding is allowed but no content is added yet  -> open Add content for first one: some its menu item can be "under" other region control buttons and it won't be possible to choose it. See example in which Markdown menu item can not be chosen:
![cms notpossibletoaddcontent](https://cloud.githubusercontent.com/assets/3446924/10788465/6d75dee0-7d80-11e5-882f-3680dd1ff159.jpg)

Issues are available under any browser

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta11+
If issue still exists, please reopen it and move into milestone v2.0

**Comment by daivabrazukaite** [comment]
Still the same (tested on Chrome, FF, Safari) using 1.11.0-beta13 version.
#1388 will be closed, as duplicate

**Comment by gerbenis** [comment]
Fix will be available in v1.11.0-beta14+

**Comment by smikulenas** [comment]
Fix available in 2.0.0-preview1+
