### ISSUE TITLE
Child Widget option value is not saved if widget is inserted into html/markdown content

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1391]
Create/edit page -> add new html content -> insert some widget that contains options into it -> edit child widget options -> make "Use default" = No and assign some new value -> close -> save content -> open for edit again and check child widget options: still "Use default" = True is available (record in bcms_root.ChildContentOptions table is created, but with value = null).
Same from markdown content.

**Comment by daivabrazukaite** [comment]
Issue exists not only by assigning value for child widget option, but also by creating new child widget option (i.e. it option is created in Edit child widget options modal) .

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta08+

**Comment by daivabrazukaite** [comment]
can not be verified until #1431 fix
