### ISSUE TITLE
It is not possible to publish page from page properties

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1392]
Create some page/blog -> open for edit page properties -> check "Page is published" = ON -> save: The record was updated by another user. Please refresh page before performing update. Try to refresh page manually and make same again: still the same
P.s.: publishing using control panel works ok; unpublishing using Edit properties - also

**Comment by smikulenas** [comment]
Fix is available in 1.11.0-beta08+
