### ISSUE TITLE
Design is needed for messages

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1406]
Old version:

![image](https://cloud.githubusercontent.com/assets/2108569/10822533/569ce7be-7e60-11e5-8651-7886d48284fd.png)

![image](https://cloud.githubusercontent.com/assets/2108569/10822791/410eb840-7e61-11e5-830d-c0c77495ace6.png)

![image](https://cloud.githubusercontent.com/assets/2108569/10822489/28438ed6-7e60-11e5-82fd-90fdb8948a9c.png)

![image](https://cloud.githubusercontent.com/assets/2108569/10822493/2d888d56-7e60-11e5-807b-cbe450571129.png)

![image](https://cloud.githubusercontent.com/assets/2108569/10822744/16ff6c8e-7e61-11e5-80f6-5857c2dc283a.png)

**Comment by Simas-Aleksandravicius** [comment]
Mockups: https://invis.io/E74TJRMGX
