### ISSUE TITLE
CkEditor -> image properties: problems with image preview

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1408]
Open any html content -> insert image to editor -> right click on inserted image -> image properties -> image info tab (default one): 
1) it is used some long lorem ipsum text in preview and because of its length, dialog height is too big and buttons in this tab even not visible depending on screen resolution/previewed image (chrome/safari).
2) if some big image is inserted and without changing its width/height in properties first alignment will be tried to set up,  image will be stretched to fit into dedicated width (chrome), or even original image will be displayed (FF)
3) Lock ratio: it is not visually clear if it is checked On or Off

**Comment by smikulenas** [comment]
This is CKEditor issue.
