### ISSUE TITLE
Markdown: some text is transformed as italic even it should not if * or _ are used inside some 'word'

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1410]
Now if you enter for example text 'Test text1_text2_text3 formatting' to markdown editor, it will be displayed as 'Test text1<i>text2</i>text3 formatting' - i.e. 'text2' will be in italic even it should not. 
Of course you can use escaping with backslash (i.e. \), but i do not think that this is correct case as per http://daringfireball.net/projects/markdown/syntax these characters could be used in the middle of word

**Comment by gerbenis** [comment]
The given article mentions that:
> Emphasis can be used in the middle of a word

In other words, our editor works as intended as we can emphasize a part of a word. Additionaly, it is mentioned that:
> For example, if you wanted to surround a word with literal asterisks (instead of an HTML <em> tag), you can use backslashes before the asterisks, like this: \*literal asterisks\*
