### ISSUE TITLE
Widget options: image folder value can be not saved

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1411]
Create/edit html widget -> options -> add new option with type "Images Folder" -> enter name -> click on value input -> click on button for folder selection -> choose some folder (go inside it and choose click "Select"): modal will be closed, chosen folder will be visible in value field, option row will be displayed in view mode. Change language to some other -> change language back: empty folder value will be presented (if you try to save, null will be saved as default value).
This issue occurs only if before opening folder selection modal, you activate value field. Visually you can distinguish if this was done or not also as after folder is selected if field was not activated option row will be displayed in edit mode and you will need to press "OK"/click anywhere else for closing edit mode - only in this case chosen folder value will be saved correct.

**Comment by daivabrazukaite** [comment]
Same issue exists for imageUrl option

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta08+
