### ISSUE TITLE
Widget in widget: problems with option created in child widget options screen

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1413]
Create widget1 -> create widget2 and add widget1 to its content -> open child widget options:
1) Leave language as Default and add new option -> you will be allowed to enter and save value, so do this. Change language: as translation is not allowed, you will see just name and type for this option in all other languages - this looks strange (if widget1 will be updated to show such an option and widget 2 will be placed to some page, default language assigned value will be visible for all languages).
2) Choose other language (language1) and add new option -> you will be allowed to enter value for this language, so do this -> Save -> Open child widget options again -> choose default language for same option: you will be allowed to enter value also, so do this again and Save. Now you will have created child option with default language and with language1 even looking to scenario#1 seems that translations should not be available
3) Leave language as Default -> add new option, enter value -> change language -> enter option edit mode (name will be allowed for edit) -> change language to Default (for it value is allowed): instead of leaving edit mode after language switch still edit mode will be presented but with empty value field.
As discussed with Mantas, maybe there is no need to have possibility to create option in widget child options screen at all - in this case all these problems will be gone? If it will be decided to leave this functionality, please review logic and make it more clear.

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta08+

**Comment by daivabrazukaite** [comment]
It is not possible to add new child widget options - ok.
