### ISSUE TITLE
Fix blog posts import

### ISSUE THREAD

**Issue by gerbenis** [devbridge/BetterCMS#1417]
The import has to ignore assigned categories

**Comment by JuliusSenkus** [comment]
Fixed, now three use cases are available:
1. Old export import (when import is only with categories ids), then import options do not matter (for categories), categories are searched by id's and if not found not assigned.
2. When new import (all category tree is exported) and "Reuse existing categories" option is selected, if category is found by id else if found by name is assigned to blog else not assigned.
3. If option "Recreate category tree" is selected then behaves as 2. but additionally creates category tree if not found.

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta09+

**Comment by daivabrazukaite** [comment]
Actually i didn't like how system behaves in scenario then "Recreate category tree" is set ON and file with post assigned to category which doesn't exists by ID, but exists by name is imported - in this case new category tree will be created, i.e. it will behave differently than using "Reuse existing..." which checks according name too and assigns last one match.
If you think that this is ok, please close task as all other stuff is checked and is ok.

**Comment by smikulenas** [comment]
Let's leave as currently implemented.
