### ISSUE TITLE
Child widget option: if widget is inserted into some page content, it should use page language in child widget options modal for value look up

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1432]
Create widget1 with some option and different values for Default language and language1 assigned and make this value visible in widget content -> open/create page for language1 -> add html/markdown content -> insert this widget to it -> open child widget options: there is no language selection as page has only one language (ok), but Default language assigned value will be visible in child widget options modal (not ok, as now value for page language should be provided). Close options, save content: correct value according page language is displayed in content - so now actually one value is used while rendering content and other provided for view/edit in child widget options modal.
Should be: widget assigned to some page content, should use page language in child widget options window. 
Related with  #1430

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta11+
