### ISSUE TITLE
Search in widgets list: incorrect widget info if widget is returned by published version name and now it is changed

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1443]
Create and publish html widget with name widgetName1 -> open it for edit, change name to widgetName2 and save as draft -> execute search by widgetName1 in widgets list: it will be provided published version name and status (i.e. widgetName1 with status Published) in the grid instead of current name and status (i.e. widgetName2 with status Published with Draft)
P.s.: in same case correct information is available in Select Widget or Usage lists.

P.s.: could be related with #1320

**Comment by gerbenis** [comment]
Fix will be available from 1.11.0-beta13+

**Comment by KarolisBab** [comment]
I managed to reproduce exactly the same issue with beta13 build.

**Comment by smikulenas** [comment]
Yep, this is correct :)
Please double check it on 1.11.0-beta14
