### ISSUE TITLE
Issue with SqlSever2008ProcessorFactory.cs not found

### ISSUE THREAD

**Issue by ssaallmmaann** [devbridge/BetterCMS#1450]
Hi,
I am trying to set up and run the project. I have following wiki steps and am able to build the solution successfully. However, when i try running/debug the projecy (F5 in VS2013) after loading, it asks for som SqlServer2008ProcessorFacroty.cs file. I opens prompt to locate one as well. I cant seem to find it in solution and not sure what file exactly is it looking for?
Guidance will help :) thanks.

**Comment by smikulenas** [comment]
Hi, VS catches some bug and tries to navigate for specific place in the code. Just hit cancel to close the modal and you should get the detailed error description.
