### ISSUE TITLE
Couple of issues to fix

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1460]
- [x] Site Settings -> Redirects -> Add New button – nothing happens.
- [x] Site Settings -> Menus -> Menu History – switching between versions will cause knockout bindings to fail http://prntscr.com/976tcg
- [x] Page sidebar menu -> Translate this page -> No validation message(required) shown for input field “New Page Language” – if you did not select language and click Clone nothing happens http://prntscr.com/976tcg
- [x] Site Settings -> Templates -> Select History -> Small Sort/Filter UI issue http://prntscr.com/976zjg
- [x] Add loader on page delete action
- [x]  Fix loader issues on history pages, all preview area should be hidden while content loads in. (table should be visible)

**Comment by gerbenis** [comment]
@paulgabronis fix 3 and 4

**Comment by paulgabronis** [comment]
@gerbenis #3 Remove validation class when language is chosen

**Comment by smikulenas** [comment]
Fix available in 2.0.0-preview1+
