### ISSUE TITLE
Local storage: images uploaded with filenames which needs encoding, are not available

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1461]
Pre-condition: local file storage is used
Upload any file which contains some symbol which needs to be encoded in its name (for example file name "Test&Test.jpg": image won't be available.

Used storage settings:
\<storage serviceType="FileSystem" contentRoot="~/uploads/" contentRootUrl="~/uploads" processTimeout="00:05:00" maxFileNameLength="100" moveDeletedFilesToTrashFolder="true" />

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta13+
