### ISSUE TITLE
Widget in page content/widget as content options: same used values should be visible in rendered html and options window

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1468]
Rendered in html and displayed in page widget/child widget "Value" column value should always match. Now it could be that in page html it is displayed one value while in options window some other value is presented in column "Value". 
Example: Create widget1 with one option without translations and value = "InitialValue" -> create page for Default language -> add content -> choose type "widget" -> choose widget1 -> open page widget options window -> set "use default" = NO and enter for example "NewValue" in "Value" column -> close page options: "NewValue" will be rendered in html (ok). Change page language: still "NewValue" will be visible in html (ok), but in page widget options window "use default" will be visible as YES and default value/value columns will contain "InitialValue" even actually it should be: use default = NO, default value = "InitialValue", value = "NewValue"

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta13+

**Comment by daivabrazukaite** [comment]
#1478
