### ISSUE TITLE
Widget in widget: if new value is assigned for some language in child widget options, no value is rendered in html if page language is different

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1478]
Create widget1 with one option and some InitialValue (no translations) -> create widget2, insert widget1 into its content -> open child widget options -> choose for example ENG language and set "Use default" = NO, enter NewValue. Insert widget2 to any page, try to change page languages: 
- default language will contain value InitialValue (ok);
- ENG language will contain value NewValue (ok)
- any other language won't contain value at all (not ok) even they have to contain InitialValue
P.s.: correct value, i.e. InitialValue, is displayed in child widget options modal for any other language - see attachment with example:
![bcms chilwidgetoptionvalue1208_1](https://cloud.githubusercontent.com/assets/3446924/11658799/56a611b8-9dcd-11e5-9977-58a8a331b83f.jpg)

**Comment by gerbenis** [comment]
Fix will be available from v1.11.0-beta14+
