### ISSUE TITLE
Widget in widget: destroyed draft values are presented in child widget options window

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1479]
Create widget1 with one option and value InitialValue (no translations), save and publish -> create widget2 -> insert widget1 into its content -> save and publish widget2 -> open widget2 for edit -> open child widget options (double click on widget1 or right click and choose "edit widget options") -> set "use default" = NO, enter DraftValue for default language, close options -> save as DRAFT widget2 -> open widget2 for edit again -> Destroy draft, press "Cancel" or "Save and Publish" (in this case DO NOT open child widget options before save) in widget2 edit window -> open widget2 for edit again and check child widget options: use default" = NO, value = DraftValue for default language is presented even actually this configuration had to be destroyed. Open widget2 history (or assign widget2 to page): correct, i.e. InitialValue will be presented there.

**Comment by gerbenis** [comment]
Fix will be available from v1.11.0-beta15+
