### ISSUE TITLE
Widget options: "Root folder" can be visible for imageUrl option type if image is not assigned

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1482]
Create widget -> open options tab -> add option with type "Image Url", leave default value field empty -> save widget -> reopen it for edit -> open again options tab: still empty "Default value" will be displayed (ok) -> add new option with type "Images Folder", also leave "Default value" input empty  -> save widget once more -> open it for edit: now for both options "Default" value is displayed as "Root folder" (not ok, as for image Url option field should be empty).
By the way, what is the original requirement for image URL - can it be empty at all? As now initially you can save option without value, but if some is already assigned, it is not possible to clear it (i guess bug is with this, so it would be nice to fix upper described issue and to fix value clearing)

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta16+

**Comment by daivabrazukaite** [comment]
Nothing is done because of clearing up chosen image Url, but let it be like this.
