### ISSUE TITLE
Page created from second level master with useDefault = No for inherited parent master option, uses incorrect page option value

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1487]
Create master1 -> add option to it with value "RootMasterValue", add html content with page option output and dynamic region -> based on master1 create master2: correct page option value will be displayed in html. Open master2 properties -> options -> set Use Default = NO and enter value "ChildMasterValue" -> save: "ChildMasterValue" will be presented in html (ok) -> create page based on master2: root master value "RootMasterValue" will be displayed in html, while actually value "ChildMasterValue" should be displayed (not ok). 
Open created page properties -> options: correct "ChildMasterValue" is available there (ok).

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta16+
