### ISSUE TITLE
Console error when editing Authors

### ISSUE THREAD

**Issue by KarolisBab** [devbridge/BetterCMS#1488]
Site settings -> Blog -> Authors

When opening an Author for edit, error appears in console:

Uncaught Error: Syntax error, unrecognized expression: #bD.extend.error @ bcms.root.min.js:16(anonymous function) @ bcms.root.min.js:49bD.extend.each @ bcms.root.min.js:16b.trigger @ bcms.root.min.js:49(anonymous function) @ bcms.root.min.js:49Z.event.dispatch @ bcms.root.min.js:16bw.handle.bx @ bcms.root.min.js:16

Save button is not working too.

**Comment by smikulenas** [comment]
Fixed available from 2.0.0-preview2+
