### ISSUE TITLE
Turn on Forms Auth for all content

### ISSUE THREAD

**Issue by cosminonea** [devbridge/BetterCMS#1534]
I am building a private content management system and I need to protect all content by turning Forms Authentication on and adding the `AuthorizeAttribute` globally.

By doing this a couple of things happened:
1. The `AuthenticationController` in the Users Module is not marked with `[AllowAnonymous]` and the browser enters an infinite loop.
2. After allowing anonymous users, all the other resources, i.e. javascript and css, are protected and the login page is not styled.

Has anyone tried this before? How would you do it?

**Comment by remyblok** [comment]
We have secured 'everything'. Basically if you turn up the Security configuration to the max, nothing gets through: https://github.com/devbridge/BetterCMS/wiki/CMS-configuration#security-configuration
```
<security accessControlEnabled="true" fullAccessRoles="Owner" encryptionEnabled="false" encryptionKey="bettercmstest">
    <defaultAccessRules defaultAccessLevel="Deny">
        <add identity="Everyone" accessLevel="Deny" isRole="true" />
        <add identity="Authenticated Users" accessLevel="Read" isRole="true" />
    </defaultAccessRules>
</security>
```

**Comment by cosminonea** [comment]
Great, thanks.
I am using ADFS now and was able to just turn off Form Auth and use only the ADFS middleware. It works great for the web content but not sure how to secure the API.

Is there any hook for specifying API authentication and permissions?
