### ISSUE TITLE
Error rendering view "~/View/Shared/Mysamplewidget.cshtml:" object reference not set to an instance of an object

### ISSUE THREAD

**Issue by DharsanaR** [devbridge/BetterCMS#1540]
I added "Base Layout model" in my custom layout page.
"@model BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel
@{
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";
}"
While adding server widget on better cms, the exception throws as "Error rendering view "~/View/Shared/Mysamplewidget.cshtml:" object reference not set to an instance of an object"

By disable the base layout, server widgets works fine but the user cannot edit the better cms.
Where I went wrong??,Kindly support ....

![untitled](https://cloud.githubusercontent.com/assets/21256697/17997070/ebf2dd98-6b89-11e6-8832-a8b4577038eb.png)

**Comment by alesdvorakcz** [comment]
Can you please post here yours widget and custom layout source code?

**Comment by DharsanaR** [comment]
Thanks for the reply,
I have fixed the issue, by adding script file on the main layout page.
