### ISSUE TITLE
When deleting media file, move real physical file to trash folder.

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#274]
When deleting media file, move real physical file to trash folder.
Create trash folder, add to settings, etc.
Do not forget, that there are more that one storage engine: in the CDN files must be moved to trash also (need to implement move function).
Change urls of deleted files in mediaFiles / mediaImages table 

Use background worker for garbage collections

**Comment by JuliusSenkus** [comment]
Fixed in 1.10.3+

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta10+

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta10+

**Comment by daivabrazukaite** [comment]
Tested with  #275
