### ISSUE TITLE
Update sidebar UX and add regions selection logic

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#442]
Sometimes contents are invisible or hidden and cannot be edited / removed. To simplify navigation need to add active region selection into sidebar.

**Comment by smikulenas** [comment]
No longer needed because of Page structure manager.

![image](https://cloud.githubusercontent.com/assets/2108569/10648751/f15421e8-7805-11e5-9ca7-a18fdc254795.png)
