### ISSUE TITLE
Media manager: implement videos tab

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#504]
- Add new tab "VIDEOS"
- Create interface for ideo provider. Create default VIMEO provider.
- Implement button "Embed video":
-- After pressing this button, video search dialog should open with ability to search in VIMEO
-- Add selected video to local database
- Implement button "Upload video"
-- After pressing this button, upload form should open, for uplading one video to VIMEO
-- Async upload should start. Do not forget, that after uploading video may be processed in VIMEO server.
-- After upload will be done new item should appear in videos grid. If file is still processing in the server, message "Video is still processing" should appear next to file.
- Implement video edit dialog, delete, etc.

**Comment by smikulenas** [comment]
Split to separate items: #1355, #1356, #1357, #1358.
