### ISSUE TITLE
Add compatibility for bootstrap v3.0.0

### ISSUE THREAD

**Issue by cordis-dev** [devbridge/BetterCMS#610]
Newly released version has some issues with various UI elements:

![misaligned-buttons](https://f.cloud.github.com/assets/1436131/1041306/fb8d53fc-0fcd-11e3-9cfe-b050ce626173.png)

![misaligned-tabs](https://f.cloud.github.com/assets/1436131/1041307/ffbfccd4-0fcd-11e3-8da5-8347a6309cfc.png)

**Comment by pauliusmaciulis** [comment]
Will be fixed with the https://github.com/devbridge/BetterCMS/issues/1005 issue.
