### ISSUE TITLE
Design issue: Edit/remove sitemap node controls

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/BetterCMS#862]
http://prntscr.com/2cjmqd

I think this is huge ui issue, there is no space between buttons, one button has text, another - not. Edit has no animated icon, remove has. 

Would be great to normalize everything here and increase spacing.

**Comment by smikulenas** [comment]
Let's fix this - use icons from page structure manager:

![image](https://cloud.githubusercontent.com/assets/2108569/10723903/6da3eb28-7bc8-11e5-87a1-d5e8fa323458.png)

**Comment by smikulenas** [comment]
Fix will be available from v2.0
