### ISSUE TITLE
As a user I want simpler UI for widget selection dialog.

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/BetterCMS#863]
http://prntscr.com/2cjn7o

In this screen we can see widgets gallery and three items. Why user has to scroll onto the widgets to see arrows for selecting another widgets? If we want to leave this functionality, maybe we can add widgets counter?
At first time it was even irritating, when we added widget and he didn't appear in widgets gallery (we didn't realised that we have to scroll over the block)

**Comment by smikulenas** [comment]
Let's use grid layout as in image selection.

To do:
 - [ ] Update widget selection dialog to use grid structure with categories column.

**Comment by smikulenas** [comment]
- [ ] Update search to search while typing
- [ ] Fix preview rendering
