### ISSUE TITLE
Create blog: it is not possible to select language

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#885]
There is no possibility to choose language during blog creation, but it is possible to set it during properties edit. I think that language selection should be in create blog also.

**Comment by smikulenas** [comment]
Agree, let's add language selection box (if multi-language language is enabled) into blog post edit dialog, under properties tab.

**Comment by smikulenas** [comment]
Fix available in 2.0.0-preview1+
