### ISSUE TITLE
Edit Capability is failing if there is a  javascript error on Page

### ISSUE THREAD

**Issue by bsatish417** [devbridge/BetterCMS#955]
Hey Guys - Edit Capability is failing when  there is a javascript error on the Razor view Widget added to a page. It is kind of hard to write code with out JS errors while developing & it is hard to edit the page  until it is fixed.  Edit should be agnostic to page or section level errors like  Kentico widgets.  

One screenshot will show the edit button but when i try to mouse over it, the edit icon group is missing ( another screenshot).
![1](https://f.cloud.github.com/assets/6218752/2084472/d01193f8-8e23-11e3-9853-0ca41bd97391.png)
![2](https://f.cloud.github.com/assets/6218752/2084473/d0129082-8e23-11e3-965e-de0c8a39108e.png)

![bug](https://f.cloud.github.com/assets/6218752/2084443/aa8b08f4-8e22-11e3-8873-970b7dab553c.png)

**Comment by AnOldMan** [comment]
I have a page with ko content, missed a required widget after adding content to regions, js breaks
```
Error: TypeError: D is undefined
Source File: https://d3hf62uppzvupw.cloudfront.net/1.10.2/bcms-root/scripts/bcms.root.min.js
Line: 49
```
sometimes get bettercms widget, but never get ability to manage content (and add missing widget).
