### ISSUE TITLE
Missing ckEditor toolbar, when specific HTML is opened in full screen mode

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#962]
Add new HTML content to the page:

Add many paragraphs, which don't fit in one screen (needs vertical scrollbar), e.g.:

~~~
<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

<p>Paragraph</p>

~~~
Save in WYSIWYG mode (not source mode)
Open content edit form
Press full screen button <img src='https://f.cloud.github.com/assets/2492600/2123257/f18b85f8-9228-11e3-9b4e-abfa070dc91c.png'> 
Toolbar is missing:

![image](https://f.cloud.github.com/assets/2492600/2123316/55d3d8a2-922a-11e3-82d4-7fded88833ea.png)

**Comment by smikulenas** [comment]
No longer relevant.
