### ISSUE TITLE
Website performance 

### ISSUE THREAD

**Issue by bsatish417** [devbridge/BetterCMS#977]
HI Team - Website is really performing slow. Is there any thing we can do to get the performance ?

Below one is on BetterCMS - http://v2.maz.aurorasuite.com/mazlogin

**Comment by mothukuriravi** [comment]
Hi Team,

All of  a sudden bettercms site is performing very slow and no code changes happened(nothing was done).Is there any specific reason for this performance issue and what could be done to resolve this issue?
